version: '3.8'
services:
  gameserver:
    image: gameserver
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - TribalGamesFirebase_Auth
secrets:
  TribalGamesFirebase_Auth:
    external: true